export interface Documentary {
  id: string;
  title: string;
  year: number;
  director: string;
  runtime: number;
  genres: string[];
  synopsis: string;
  featuring: string[];
  poster: string;
  backdrop: string;
  language: string;
  country: string;
  platform: string;
  avgRating: number;
  ratingsCount: number;
}

export const DOCS: Documentary[] = [
  {
    id: 'doc-planet-earth-ii',
    title: 'Planet Earth II',
    year: 2016,
    director: 'Justin Anderson, Chadden Hunter',
    runtime: 360,
    genres: ['Nature', 'Science'],
    synopsis: 'David Attenborough narrates this landmark series exploring the natural world from the mountains to the cities, revealing animal behavior never captured on film before.',
    featuring: ['David Attenborough'],
    poster: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'UK',
    platform: 'BBC / Netflix',
    avgRating: 9.5,
    ratingsCount: 18700,
  },
  {
    id: 'doc-making-a-murderer',
    title: 'Making a Murderer',
    year: 2015,
    director: 'Laura Ricciardi, Moira Demos',
    runtime: 540,
    genres: ['True Crime', 'Legal'],
    synopsis: 'Filmed over 10 years, this series follows Steven Avery of Manitowoc County, Wisconsin, who — after spending 18 years in prison for a wrongful conviction — is arrested for murder.',
    featuring: ['Steven Avery', 'Brendan Dassey', 'Dean Strang', 'Jerome Buting'],
    poster: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Netflix',
    avgRating: 8.6,
    ratingsCount: 14200,
  },
  {
    id: 'doc-free-solo',
    title: 'Free Solo',
    year: 2018,
    director: 'Elizabeth Chai Vasarhelyi, Jimmy Chin',
    runtime: 100,
    genres: ['Sports', 'Adventure', 'Biography'],
    synopsis: 'Follow Alex Honnold as he attempts to become the first person to ever free solo climb Yosemite\'s El Capitan — a 3,000-foot vertical rock face — with no ropes or safety gear.',
    featuring: ['Alex Honnold', 'Tommy Caldwell'],
    poster: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'National Geographic',
    avgRating: 8.2,
    ratingsCount: 11900,
  },
  {
    id: 'doc-the-jinx',
    title: 'The Jinx: The Life and Deaths of Robert Durst',
    year: 2015,
    director: 'Andrew Jarecki',
    runtime: 360,
    genres: ['True Crime'],
    synopsis: 'Filmmaker Andrew Jarecki gained exclusive access to real-estate heir Robert Durst, who has long been a suspect in multiple murders including that of his wife, a writer, and his best friend.',
    featuring: ['Robert Durst', 'Andrew Jarecki'],
    poster: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'HBO',
    avgRating: 8.8,
    ratingsCount: 9300,
  },
  {
    id: 'doc-amy',
    title: 'Amy',
    year: 2015,
    director: 'Asif Kapadia',
    runtime: 128,
    genres: ['Music', 'Biography'],
    synopsis: 'The story of Amy Winehouse in her own words, featuring archival footage and unheard tracks. A portrait of an intensely talented girl who had everything and lost it all.',
    featuring: ['Amy Winehouse', 'Mitch Winehouse', 'Mark Ronson'],
    poster: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'UK',
    platform: 'A24 / Amazon',
    avgRating: 8.1,
    ratingsCount: 10700,
  },
  {
    id: 'doc-13th',
    title: '13th',
    year: 2016,
    director: 'Ava DuVernay',
    runtime: 100,
    genres: ['Social', 'History', 'Politics'],
    synopsis: 'An in-depth look at the prison system in the United States and how it reveals the nation\'s history of racial inequality.',
    featuring: ['Jelani Cobb', 'Henry Louis Gates Jr.', 'Van Jones', 'Bryan Stevenson'],
    poster: 'https://images.unsplash.com/photo-1575505586569-646b2ca898fc?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Netflix',
    avgRating: 8.2,
    ratingsCount: 12400,
  },
  {
    id: 'doc-man-on-wire',
    title: 'Man on Wire',
    year: 2008,
    director: 'James Marsh',
    runtime: 94,
    genres: ['Biography', 'History', 'Sports'],
    synopsis: 'A look at tightrope walker Philippe Petit\'s 1974 high-wire walk between the World Trade Center\'s twin towers — a walk he described as "the artistic crime of the century."',
    featuring: ['Philippe Petit', 'Jean-François Heckel'],
    poster: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=1200&h=600&fit=crop',
    language: 'English/French',
    country: 'UK/USA',
    platform: 'Magnolia Pictures',
    avgRating: 7.9,
    ratingsCount: 8800,
  },
  {
    id: 'doc-searching-for-sugar-man',
    title: 'Searching for Sugar Man',
    year: 2012,
    director: 'Malik Bendjelloul',
    runtime: 86,
    genres: ['Music', 'Biography', 'Mystery'],
    synopsis: 'Two South Africans search for their hero Rodriguez, a 70s US musician, who inspired their generation but had no idea of the profound effect his music had on their lives.',
    featuring: ['Sixto Rodriguez', 'Stephen Segerman'],
    poster: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'Sweden/UK',
    platform: 'Sony Pictures Classics',
    avgRating: 8.2,
    ratingsCount: 7600,
  },
  {
    id: 'doc-icarus',
    title: 'Icarus',
    year: 2017,
    director: 'Bryan Fogel',
    runtime: 121,
    genres: ['Sports', 'True Crime', 'Politics'],
    synopsis: 'What begins as a personal experiment into doping in amateur sports turns into an explosive investigation of the Russian government\'s systematic manipulation of the Olympic Games.',
    featuring: ['Bryan Fogel', 'Grigory Rodchenkov'],
    poster: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&h=600&fit=crop',
    language: 'English/Russian',
    country: 'USA',
    platform: 'Netflix',
    avgRating: 7.9,
    ratingsCount: 8200,
  },
  {
    id: 'doc-wild-wild-country',
    title: 'Wild Wild Country',
    year: 2018,
    director: 'Chapman Way, Maclain Way',
    runtime: 360,
    genres: ['True Crime', 'Religion', 'History'],
    synopsis: 'When the followers of Indian guru Bhagwan Shree Rajneesh build a utopian city in rural Oregon, a conflict with locals escalates into the world\'s first bioterrorism attack in the US.',
    featuring: ['Ma Anand Sheela', 'Bhagwan Shree Rajneesh', 'Jane Stork'],
    poster: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Netflix',
    avgRating: 8.1,
    ratingsCount: 9100,
  },
  {
    id: 'doc-the-last-dance',
    title: 'The Last Dance',
    year: 2020,
    director: 'Jason Hehir',
    runtime: 500,
    genres: ['Sports', 'Biography', 'History'],
    synopsis: 'A documentary series on the 1997-98 Chicago Bulls, the greatest basketball dynasty of all time, featuring unprecedented access to Michael Jordan and his team.',
    featuring: ['Michael Jordan', 'Scottie Pippen', 'Dennis Rodman', 'Phil Jackson'],
    poster: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Netflix / ESPN',
    avgRating: 9.1,
    ratingsCount: 21300,
  },
  {
    id: 'doc-my-octopus-teacher',
    title: 'My Octopus Teacher',
    year: 2020,
    director: 'Pippa Ehrlich, James Reed',
    runtime: 85,
    genres: ['Nature', 'Biography'],
    synopsis: 'A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning what it feels like to be a wild creature.',
    featuring: ['Craig Foster'],
    poster: 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'South Africa',
    platform: 'Netflix',
    avgRating: 8.1,
    ratingsCount: 13500,
  },
  {
    id: 'doc-the-social-dilemma',
    title: 'The Social Dilemma',
    year: 2020,
    director: 'Jeff Orlowski',
    runtime: 94,
    genres: ['Technology', 'Social', 'Politics'],
    synopsis: 'Tech experts sound the alarm on the dangerous human impact of social networking, shedding light on how social media platforms are designed to be addictive.',
    featuring: ['Tristan Harris', 'Jaron Lanier', 'Roger McNamee', 'Aza Raskin'],
    poster: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Netflix',
    avgRating: 7.6,
    ratingsCount: 16200,
  },
  {
    id: 'doc-david-attenborough-life-on-our-planet',
    title: 'David Attenborough: A Life on Our Planet',
    year: 2020,
    director: 'Alastair Fothergill, Jonathan Hughes, Keith Scholey',
    runtime: 83,
    genres: ['Nature', 'Science', 'Biography'],
    synopsis: 'David Attenborough shares his witness statement and a vision for the future in this inspiring film about the natural world he has spent his life exploring.',
    featuring: ['David Attenborough'],
    poster: 'https://images.unsplash.com/photo-1498598457418-36ef20772bb9?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'UK',
    platform: 'Netflix',
    avgRating: 9.0,
    ratingsCount: 17800,
  },
  {
    id: 'doc-senna',
    title: 'Senna',
    year: 2010,
    director: 'Asif Kapadia',
    runtime: 106,
    genres: ['Sports', 'Biography', 'History'],
    synopsis: 'A documentary on Brazilian Formula One racing driver Ayrton Senna, who won the F1 World Championship three times before his death at age 34.',
    featuring: ['Ayrton Senna', 'Alain Prost', 'Frank Williams'],
    poster: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop',
    language: 'English/Portuguese',
    country: 'UK/Brazil',
    platform: 'Universal Pictures',
    avgRating: 8.5,
    ratingsCount: 9400,
  },
  {
    id: 'doc-cant-stop-wont-stop',
    title: "Won't You Be My Neighbor?",
    year: 2018,
    director: 'Morgan Neville',
    runtime: 94,
    genres: ['Biography', 'Social'],
    synopsis: 'An exploration of the life, lessons, and legacy of Fred Rogers, the beloved host of Mister Rogers\' Neighborhood, and his legacy of kindness.',
    featuring: ['Fred Rogers', 'Joanne Rogers', 'François Clemmons'],
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1500259571355-332da5cb07aa?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Focus Features',
    avgRating: 8.4,
    ratingsCount: 8100,
  },
  {
    id: 'doc-super-size-me',
    title: 'Super Size Me',
    year: 2004,
    director: 'Morgan Spurlock',
    runtime: 100,
    genres: ['Food', 'Health', 'Social'],
    synopsis: 'Filmmaker Morgan Spurlock personally explores the consequences of eating exclusively at McDonald\'s for one month.',
    featuring: ['Morgan Spurlock'],
    poster: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Samuel Goldwyn Films',
    avgRating: 7.2,
    ratingsCount: 12100,
  },
  {
    id: 'doc-jiro-dreams-of-sushi',
    title: 'Jiro Dreams of Sushi',
    year: 2011,
    director: 'David Gelb',
    runtime: 81,
    genres: ['Food', 'Biography', 'Culture'],
    synopsis: 'A profile of 85-year-old sushi master Jiro Ono and his world-renowned restaurant Sukiyabashi Jiro, a tiny basement restaurant in a Tokyo subway station.',
    featuring: ['Jiro Ono', 'Yoshikazu Ono'],
    poster: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=600&fit=crop',
    language: 'Japanese',
    country: 'USA/Japan',
    platform: 'Magnolia Pictures',
    avgRating: 7.9,
    ratingsCount: 7600,
  },
  {
    id: 'doc-dont-look-up-the-act-of-killing',
    title: 'The Act of Killing',
    year: 2012,
    director: 'Joshua Oppenheimer',
    runtime: 115,
    genres: ['History', 'Politics', 'War'],
    synopsis: 'A documentary which challenges former Indonesian death squad leaders to reenact their mass killings in whatever cinematic genres they wish.',
    featuring: ['Anwar Congo', 'Herman Koto'],
    poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1527525443983-6e60c75fff46?w=1200&h=600&fit=crop',
    language: 'Indonesian',
    country: 'Denmark/Norway/UK',
    platform: 'Drafthouse Films',
    avgRating: 8.2,
    ratingsCount: 6700,
  },
  {
    id: 'doc-tiger-king',
    title: 'Tiger King: Murder, Mayhem and Madness',
    year: 2020,
    director: 'Eric Goode, Rebecca Chaiklin',
    runtime: 420,
    genres: ['True Crime', 'Nature'],
    synopsis: 'A rivalry between big cat eccentrics Joe Exotic and Carole Baskin explodes into a criminal investigation. An utterly strange, compelling descent into a world unlike any other.',
    featuring: ['Joe Exotic', 'Carole Baskin', 'Doc Antle'],
    poster: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Netflix',
    avgRating: 7.5,
    ratingsCount: 19700,
  },
  {
    id: 'doc-stutz',
    title: 'Stutz',
    year: 2022,
    director: 'Jonah Hill',
    runtime: 95,
    genres: ['Biography', 'Mental Health'],
    synopsis: 'Jonah Hill explores his relationship with his psychiatrist, Dr. Phil Stutz, sharing the doctors innovative tools and philosophy with the world.',
    featuring: ['Jonah Hill', 'Phil Stutz'],
    poster: 'https://images.unsplash.com/photo-1516641051054-9df6a1aad654?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    platform: 'Netflix',
    avgRating: 7.8,
    ratingsCount: 6300,
  },
  {
    id: 'doc-the-imposter',
    title: 'The Imposter',
    year: 2012,
    director: 'Bart Layton',
    runtime: 99,
    genres: ['True Crime', 'Mystery'],
    synopsis: 'A documentary about the strange story of a French con man who in 1997 claimed to be a missing Texas boy — who had been missing for three years.',
    featuring: ['Frédéric Bourdin', 'Carey Gibson', 'Beverly Dollarhide'],
    poster: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1555548180-61e9b6e44b53?w=1200&h=600&fit=crop',
    language: 'English/French/Spanish',
    country: 'UK',
    platform: 'Picturehouse Entertainment',
    avgRating: 7.4,
    ratingsCount: 5200,
  },
];

export const DOC_MAP = new Map(DOCS.map(d => [d.id, d]));

export function searchDocs(query: string): Documentary[] {
  const q = query.toLowerCase();
  return DOCS.filter(d =>
    d.title.toLowerCase().includes(q) ||
    d.director.toLowerCase().includes(q) ||
    d.genres.some(g => g.toLowerCase().includes(q)) ||
    d.featuring.some(f => f.toLowerCase().includes(q)) ||
    d.platform.toLowerCase().includes(q) ||
    d.year.toString().includes(q)
  );
}

export function getDoc(id: string): Documentary | undefined {
  return DOC_MAP.get(id);
}
