// Curated movie catalog with rich data
export interface Movie {
  id: string;
  title: string;
  year: number;
  director: string;
  runtime: number;
  genres: string[];
  synopsis: string;
  cast: string[];
  poster: string; // Unsplash or gradient placeholder
  backdrop: string;
  language: string;
  country: string;
  avgRating: number; // out of 10
  ratingsCount: number;
}

export const MOVIES: Movie[] = [
  {
    id: 'tt0111161',
    title: 'The Shawshank Redemption',
    year: 1994,
    director: 'Frank Darabont',
    runtime: 142,
    genres: ['Drama'],
    synopsis: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic human decency.',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'],
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 9.3,
    ratingsCount: 28420,
  },
  {
    id: 'tt0068646',
    title: 'The Godfather',
    year: 1972,
    director: 'Francis Ford Coppola',
    runtime: 175,
    genres: ['Crime', 'Drama'],
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton'],
    poster: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 9.2,
    ratingsCount: 24810,
  },
  {
    id: 'tt0468569',
    title: 'The Dark Knight',
    year: 2008,
    director: 'Christopher Nolan',
    runtime: 152,
    genres: ['Action', 'Crime', 'Drama'],
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Maggie Gyllenhaal'],
    poster: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    avgRating: 9.0,
    ratingsCount: 31250,
  },
  {
    id: 'tt1375666',
    title: 'Inception',
    year: 2010,
    director: 'Christopher Nolan',
    runtime: 148,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    avgRating: 8.8,
    ratingsCount: 29100,
  },
  {
    id: 'tt0110912',
    title: 'Pulp Fiction',
    year: 1994,
    director: 'Quentin Tarantino',
    runtime: 154,
    genres: ['Crime', 'Drama'],
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    poster: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 8.9,
    ratingsCount: 26700,
  },
  {
    id: 'tt0137523',
    title: 'Fight Club',
    year: 1999,
    director: 'David Fincher',
    runtime: 139,
    genres: ['Drama'],
    synopsis: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter', 'Meat Loaf'],
    poster: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/Germany',
    avgRating: 8.8,
    ratingsCount: 23900,
  },
  {
    id: 'tt0245429',
    title: 'Spirited Away',
    year: 2001,
    director: 'Hayao Miyazaki',
    runtime: 125,
    genres: ['Animation', 'Adventure', 'Family'],
    synopsis: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.',
    cast: ['Daveigh Chase', 'Suzanne Pleshette', 'Miyu Irino', 'Rumi Hiiragi'],
    poster: 'https://images.unsplash.com/photo-1560472355-536de3962603?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&h=600&fit=crop',
    language: 'Japanese',
    country: 'Japan',
    avgRating: 9.0,
    ratingsCount: 18400,
  },
  {
    id: 'tt0816692',
    title: 'Interstellar',
    year: 2014,
    director: 'Christopher Nolan',
    runtime: 169,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    synopsis: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    poster: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    avgRating: 8.7,
    ratingsCount: 27300,
  },
  {
    id: 'tt0109830',
    title: 'Forrest Gump',
    year: 1994,
    director: 'Robert Zemeckis',
    runtime: 142,
    genres: ['Drama', 'Romance'],
    synopsis: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Sally Field'],
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1500259571355-332da5cb07aa?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 8.8,
    ratingsCount: 25100,
  },
  {
    id: 'tt0120737',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 2001,
    director: 'Peter Jackson',
    runtime: 178,
    genres: ['Adventure', 'Drama', 'Fantasy'],
    synopsis: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom', 'Sean Bean'],
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'New Zealand/USA',
    avgRating: 8.9,
    ratingsCount: 22600,
  },
  {
    id: 'tt0167260',
    title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    director: 'Peter Jackson',
    runtime: 201,
    genres: ['Adventure', 'Drama', 'Fantasy'],
    synopsis: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    cast: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen', 'Liv Tyler'],
    poster: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'New Zealand/USA',
    avgRating: 9.0,
    ratingsCount: 21900,
  },
  {
    id: 'tt0133093',
    title: 'The Matrix',
    year: 1999,
    director: 'Lana Wachowski, Lilly Wachowski',
    runtime: 136,
    genres: ['Action', 'Sci-Fi'],
    synopsis: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/Australia',
    avgRating: 8.7,
    ratingsCount: 24500,
  },
  {
    id: 'tt0482571',
    title: 'The Prestige',
    year: 2006,
    director: 'Christopher Nolan',
    runtime: 130,
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    synopsis: 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
    cast: ['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson', 'Michael Caine'],
    poster: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    avgRating: 8.5,
    ratingsCount: 18700,
  },
  {
    id: 'tt0088763',
    title: 'Back to the Future',
    year: 1985,
    director: 'Robert Zemeckis',
    runtime: 116,
    genres: ['Adventure', 'Comedy', 'Sci-Fi'],
    synopsis: 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean automobile built by eccentric scientist Doc Brown.',
    cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson', 'Crispin Glover'],
    poster: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 8.5,
    ratingsCount: 19800,
  },
  {
    id: 'tt0120689',
    title: 'The Green Mile',
    year: 1999,
    director: 'Frank Darabont',
    runtime: 189,
    genres: ['Crime', 'Drama', 'Fantasy'],
    synopsis: 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
    cast: ['Tom Hanks', 'Michael Clarke Duncan', 'David Morse', 'Bonnie Hunt'],
    poster: 'https://images.unsplash.com/photo-1505904267569-f02eaeb45a4c?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 8.6,
    ratingsCount: 17200,
  },
  {
    id: 'tt0114369',
    title: 'Se7en',
    year: 1995,
    director: 'David Fincher',
    runtime: 127,
    genres: ['Crime', 'Drama', 'Mystery'],
    synopsis: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    cast: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey', 'Gwyneth Paltrow'],
    poster: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 8.6,
    ratingsCount: 20100,
  },
  {
    id: 'tt0108052',
    title: "Schindler's List",
    year: 1993,
    director: 'Steven Spielberg',
    runtime: 195,
    genres: ['Biography', 'Drama', 'History'],
    synopsis: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    cast: ['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley', 'Caroline Goodall'],
    poster: 'https://images.unsplash.com/photo-1467703834117-04386e3dadd8?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1527525443983-6e60c75fff46?w=1200&h=600&fit=crop',
    language: 'English/Hebrew/German',
    country: 'USA',
    avgRating: 9.0,
    ratingsCount: 22400,
  },
  {
    id: 'tt0172495',
    title: 'Gladiator',
    year: 2000,
    director: 'Ridley Scott',
    runtime: 155,
    genres: ['Action', 'Adventure', 'Drama'],
    synopsis: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Oliver Reed'],
    poster: 'https://images.unsplash.com/photo-1555548180-61e9b6e44b53?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    avgRating: 8.5,
    ratingsCount: 21000,
  },
  {
    id: 'tt0071562',
    title: 'The Godfather Part II',
    year: 1974,
    director: 'Francis Ford Coppola',
    runtime: 202,
    genres: ['Crime', 'Drama'],
    synopsis: 'The early life and career of Vito Corleone in 1920s New York City is portrayed while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    cast: ['Al Pacino', 'Robert De Niro', 'Robert Duvall', 'Diane Keaton'],
    poster: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=1200&h=600&fit=crop',
    language: 'English/Italian/Spanish',
    country: 'USA',
    avgRating: 9.0,
    ratingsCount: 19800,
  },
  {
    id: 'tt0993846',
    title: 'The Wolf of Wall Street',
    year: 2013,
    director: 'Martin Scorsese',
    runtime: 180,
    genres: ['Biography', 'Comedy', 'Crime'],
    synopsis: 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker living the high life to his fall involving crime, corruption and the federal government.',
    cast: ['Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie', 'Matthew McConaughey'],
    poster: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    avgRating: 8.2,
    ratingsCount: 23700,
  },
];

export const MOVIE_MAP = new Map(MOVIES.map(m => [m.id, m]));

export function searchMovies(query: string): Movie[] {
  const q = query.toLowerCase();
  return MOVIES.filter(m =>
    m.title.toLowerCase().includes(q) ||
    m.director.toLowerCase().includes(q) ||
    m.genres.some(g => g.toLowerCase().includes(q)) ||
    m.cast.some(c => c.toLowerCase().includes(q)) ||
    m.year.toString().includes(q)
  );
}

export function getMovie(id: string): Movie | undefined {
  return MOVIE_MAP.get(id);
}

export function starsFromRating(r: number): string {
  // Convert 1-10 to 0.5-5 stars
  const stars = r / 2;
  const full = Math.floor(stars);
  const half = stars % 1 >= 0.5 ? 1 : 0;
  return '★'.repeat(full) + (half ? '½' : '') + '☆'.repeat(5 - full - half);
}
