export interface TVShow {
  id: string;
  title: string;
  firstAired: number;
  creator: string;
  seasons: number;
  episodes: number;
  genres: string[];
  synopsis: string;
  cast: string[];
  poster: string;
  backdrop: string;
  language: string;
  country: string;
  network: string;
  status: 'Ended' | 'Ongoing';
  avgRating: number;
  ratingsCount: number;
}

export const SHOWS: TVShow[] = [
  {
    id: 'tt0903747',
    title: 'Breaking Bad',
    firstAired: 2008,
    creator: 'Vince Gilligan',
    seasons: 5,
    episodes: 62,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn', 'Dean Norris'],
    poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'AMC',
    status: 'Ended',
    avgRating: 9.5,
    ratingsCount: 41200,
  },
  {
    id: 'tt0141842',
    title: 'The Sopranos',
    firstAired: 1999,
    creator: 'David Chase',
    seasons: 6,
    episodes: 86,
    genres: ['Crime', 'Drama'],
    synopsis: 'New Jersey mob boss Tony Soprano deals with personal and professional difficulties as he attends therapy sessions with a psychiatrist.',
    cast: ['James Gandolfini', 'Lorraine Bracco', 'Edie Falco', 'Michael Imperioli'],
    poster: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ended',
    avgRating: 9.2,
    ratingsCount: 29800,
  },
  {
    id: 'tt0306414',
    title: 'The Wire',
    firstAired: 2002,
    creator: 'David Simon',
    seasons: 5,
    episodes: 60,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.',
    cast: ['Dominic West', 'Lance Reddick', 'Idris Elba', 'John Doman'],
    poster: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ended',
    avgRating: 9.3,
    ratingsCount: 22100,
  },
  {
    id: 'tt7660850',
    title: 'Succession',
    firstAired: 2018,
    creator: 'Jesse Armstrong',
    seasons: 4,
    episodes: 39,
    genres: ['Drama', 'Satire'],
    synopsis: 'The Roy family, the owners of a global media and hospitality empire, are fighting for control of their company while confronting the possibility of their aging father\'s retirement.',
    cast: ['Brian Cox', 'Jeremy Strong', 'Sarah Snook', 'Kieran Culkin'],
    poster: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ended',
    avgRating: 9.0,
    ratingsCount: 18700,
  },
  {
    id: 'tt3032476',
    title: 'Better Call Saul',
    firstAired: 2015,
    creator: 'Vince Gilligan, Peter Gould',
    seasons: 6,
    episodes: 63,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'The trials and tribulations of criminal lawyer Jimmy McGill in the time leading up to establishing his strip-mall law office in Albuquerque, New Mexico.',
    cast: ['Bob Odenkirk', 'Jonathan Banks', 'Rhea Seehorn', 'Patrick Fabian'],
    poster: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'AMC',
    status: 'Ended',
    avgRating: 8.9,
    ratingsCount: 16400,
  },
  {
    id: 'tt5687612',
    title: 'Fleabag',
    firstAired: 2016,
    creator: 'Phoebe Waller-Bridge',
    seasons: 2,
    episodes: 12,
    genres: ['Comedy', 'Drama'],
    synopsis: 'A dry-witted woman navigates life and love in London, breaking the fourth wall to share her most intimate thoughts.',
    cast: ['Phoebe Waller-Bridge', 'Sian Clifford', 'Olivia Colman', 'Andrew Scott'],
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'UK',
    network: 'BBC Three / Amazon',
    status: 'Ended',
    avgRating: 8.7,
    ratingsCount: 11300,
  },
  {
    id: 'tt7366338',
    title: 'Chernobyl',
    firstAired: 2019,
    creator: 'Craig Mazin',
    seasons: 1,
    episodes: 5,
    genres: ['Drama', 'History', 'Thriller'],
    synopsis: 'In April 1986, an explosion at the Chernobyl nuclear power plant in the USSR becomes one of the world\'s worst man-made catastrophes.',
    cast: ['Jared Harris', 'Stellan Skarsgård', 'Emily Watson', 'Paul Ritter'],
    poster: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    network: 'HBO',
    status: 'Ended',
    avgRating: 9.4,
    ratingsCount: 17600,
  },
  {
    id: 'tt0185906',
    title: 'Band of Brothers',
    firstAired: 2001,
    creator: 'Steven Spielberg, Tom Hanks',
    seasons: 1,
    episodes: 10,
    genres: ['Action', 'Drama', 'History', 'War'],
    synopsis: 'The story of Easy Company of the US Army 101st Airborne division, from their initial training through their participation in major battles in Europe during WWII.',
    cast: ['Damian Lewis', 'Ron Livingston', 'Scott Grimes', 'Donnie Wahlberg'],
    poster: 'https://images.unsplash.com/photo-1467703834117-04386e3dadd8?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1527525443983-6e60c75fff46?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    network: 'HBO',
    status: 'Ended',
    avgRating: 9.4,
    ratingsCount: 14900,
  },
  {
    id: 'tt11280740',
    title: 'Severance',
    firstAired: 2022,
    creator: 'Dan Erickson',
    seasons: 2,
    episodes: 19,
    genres: ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
    synopsis: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.',
    cast: ['Adam Scott', 'Zach Cherry', 'Britt Lower', 'Tramell Tillman'],
    poster: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'Apple TV+',
    status: 'Ongoing',
    avgRating: 8.8,
    ratingsCount: 13200,
  },
  {
    id: 'tt14452776',
    title: 'The Bear',
    firstAired: 2022,
    creator: 'Christopher Storer',
    seasons: 3,
    episodes: 28,
    genres: ['Comedy', 'Drama'],
    synopsis: 'A young chef from the fine dining world returns home to run his family\'s sandwich shop in Chicago, navigating chaotic kitchen culture and his own grief.',
    cast: ['Jeremy Allen White', 'Ebon Moss-Bachrach', 'Ayo Edebiri', 'Lionel Boyce'],
    poster: 'https://images.unsplash.com/photo-1555548180-61e9b6e44b53?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'FX / Hulu',
    status: 'Ongoing',
    avgRating: 8.7,
    ratingsCount: 12100,
  },
  {
    id: 'tt0804503',
    title: 'Mad Men',
    firstAired: 2007,
    creator: 'Matthew Weiner',
    seasons: 7,
    episodes: 92,
    genres: ['Drama'],
    synopsis: 'A drama about one of New York\'s most prestigious ad agencies at the beginning of the 1960s, focusing on one of the agency\'s most mysterious but extremely talented ad executives, Donald Draper.',
    cast: ['Jon Hamm', 'Elisabeth Moss', 'Vincent Kartheiser', 'January Jones'],
    poster: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'AMC',
    status: 'Ended',
    avgRating: 8.6,
    ratingsCount: 14800,
  },
  {
    id: 'tt2149175',
    title: 'The Americans',
    firstAired: 2013,
    creator: 'Joe Weisberg',
    seasons: 6,
    episodes: 75,
    genres: ['Crime', 'Drama', 'Mystery', 'Thriller'],
    synopsis: 'Two KGB spies pose as a married American couple in suburban Washington, D.C. shortly after Ronald Reagan is elected President.',
    cast: ['Keri Russell', 'Matthew Rhys', 'Noah Emmerich', 'Holly Taylor'],
    poster: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'FX',
    status: 'Ended',
    avgRating: 8.5,
    ratingsCount: 10200,
  },
  {
    id: 'tt4158110',
    title: 'Mr. Robot',
    firstAired: 2015,
    creator: 'Sam Esmail',
    seasons: 4,
    episodes: 45,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'Elliot, a brilliant but highly unstable young cyber-security engineer and vigilante hacker, becomes a key figure in a global cyberterrorism organization.',
    cast: ['Rami Malek', 'Christian Slater', 'Portia Doubleday', 'Carly Chaikin'],
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'USA Network',
    status: 'Ended',
    avgRating: 8.5,
    ratingsCount: 12800,
  },
  {
    id: 'tt2699128',
    title: 'The Leftovers',
    firstAired: 2014,
    creator: 'Damon Lindelof, Tom Perrotta',
    seasons: 3,
    episodes: 28,
    genres: ['Drama', 'Fantasy', 'Mystery'],
    synopsis: 'The sudden disappearance of 2% of the world\'s population causes those left behind to deal with the emotional fallout of the unexplained event.',
    cast: ['Justin Theroux', 'Carrie Coon', 'Ann Dowd', 'Chris Eccleston'],
    poster: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ended',
    avgRating: 8.3,
    ratingsCount: 8700,
  },
  {
    id: 'tt0944947',
    title: 'Game of Thrones',
    firstAired: 2011,
    creator: 'David Benioff, D.B. Weiss',
    seasons: 8,
    episodes: 73,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    synopsis: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    cast: ['Emilia Clarke', 'Peter Dinklage', 'Kit Harington', 'Lena Headey'],
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA/UK',
    network: 'HBO',
    status: 'Ended',
    avgRating: 8.4,
    ratingsCount: 38600,
  },
  {
    id: 'tt2802850',
    title: 'Fargo',
    firstAired: 2014,
    creator: 'Noah Hawley',
    seasons: 5,
    episodes: 51,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'Various chronicles of deception, intrigue, and murder in and around frozen Minnesota. Yet all of these tales mysteriously lead back one way or another to Fargo, North Dakota.',
    cast: ['Billy Bob Thornton', 'Martin Freeman', 'Allison Tolman', 'Bob Odenkirk'],
    poster: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'FX',
    status: 'Ongoing',
    avgRating: 8.9,
    ratingsCount: 13500,
  },
  {
    id: 'tt2356777',
    title: 'True Detective',
    firstAired: 2014,
    creator: 'Nic Pizzolatto',
    seasons: 4,
    episodes: 32,
    genres: ['Crime', 'Drama', 'Mystery', 'Thriller'],
    synopsis: 'Anthology crime series in which a single investigation takes place over many years, with a seasoned detective and his younger partner solving a ritualistic murder in the Louisiana bayou.',
    cast: ['Matthew McConaughey', 'Woody Harrelson', 'Colin Farrell', 'Rachel McAdams'],
    poster: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ongoing',
    avgRating: 9.0,
    ratingsCount: 19200,
  },
  {
    id: 'tt2442560',
    title: 'Peaky Blinders',
    firstAired: 2013,
    creator: 'Steven Knight',
    seasons: 6,
    episodes: 36,
    genres: ['Crime', 'Drama', 'History'],
    synopsis: 'A gangster family epic set in 1919 Birmingham, England, centering on the Shelby crime family and their ambitious and ruthless patriarch Tommy Shelby.',
    cast: ['Cillian Murphy', 'Sam Neill', 'Helen McCrory', 'Paul Anderson'],
    poster: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'UK',
    network: 'BBC Two / Netflix',
    status: 'Ended',
    avgRating: 8.8,
    ratingsCount: 23100,
  },
  {
    id: 'tt4574334',
    title: 'Stranger Things',
    firstAired: 2016,
    creator: 'Duffer Brothers',
    seasons: 4,
    episodes: 34,
    genres: ['Drama', 'Fantasy', 'Horror', 'Mystery', 'Sci-Fi'],
    synopsis: 'When a young boy disappears in Hawkins, Indiana, his friends, family, and local police discover a series of extraordinary mysteries involving secret government experiments and terrifying supernatural forces.',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'David Harbour', 'Winona Ryder'],
    poster: 'https://images.unsplash.com/photo-1560472355-536de3962603?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'Netflix',
    status: 'Ongoing',
    avgRating: 8.7,
    ratingsCount: 31400,
  },
  {
    id: 'tt7126948',
    title: 'Mindhunter',
    firstAired: 2017,
    creator: 'Joe Penhall',
    seasons: 2,
    episodes: 19,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder and establishing the so-called "Mindhunter" division.',
    cast: ['Jonathan Groff', 'Holt McCallany', 'Anna Torv', 'Cameron Britton'],
    poster: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'Netflix',
    status: 'Ended',
    avgRating: 8.6,
    ratingsCount: 14700,
  },
  {
    id: 'tt5071412',
    title: 'Ozark',
    firstAired: 2017,
    creator: 'Bill Dubuque, Mark Williams',
    seasons: 4,
    episodes: 44,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.',
    cast: ['Jason Bateman', 'Laura Linney', 'Sofia Hublitz', 'Julia Garner'],
    poster: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'Netflix',
    status: 'Ended',
    avgRating: 8.4,
    ratingsCount: 17600,
  },
  {
    id: 'tt5753856',
    title: 'Dark',
    firstAired: 2017,
    creator: 'Baran bo Odar, Jantje Friese',
    seasons: 3,
    episodes: 26,
    genres: ['Crime', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
    synopsis: 'A family saga with a supernatural twist, set in a German town where the disappearance of two children exposes the relationships among four families whose hidden pasts include a time travel conspiracy spanning several generations.',
    cast: ['Louis Hofmann', 'Karoline Eichhorn', 'Lisa Vicari', 'Maja Schöne'],
    poster: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&h=600&fit=crop',
    language: 'German',
    country: 'Germany',
    network: 'Netflix',
    status: 'Ended',
    avgRating: 8.8,
    ratingsCount: 12900,
  },
  {
    id: 'tt6468322',
    title: 'Money Heist',
    firstAired: 2017,
    creator: 'Álex Pina',
    seasons: 5,
    episodes: 41,
    genres: ['Action', 'Crime', 'Drama', 'Mystery', 'Thriller'],
    synopsis: 'A criminal mastermind who goes by "The Professor" has a plan to pull off the biggest heist in recorded history: to print billions of euros in the Royal Mint of Spain.',
    cast: ['Álvaro Morte', 'Itziar Ituño', 'Úrsula Corberó', 'Miguel Herrán'],
    poster: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=600&fit=crop',
    language: 'Spanish',
    country: 'Spain',
    network: 'Netflix',
    status: 'Ended',
    avgRating: 8.2,
    ratingsCount: 26300,
  },
  {
    id: 'tt7335184',
    title: 'Barry',
    firstAired: 2018,
    creator: 'Alec Berg, Bill Hader',
    seasons: 4,
    episodes: 32,
    genres: ['Comedy', 'Crime', 'Drama', 'Thriller'],
    synopsis: 'A hitman from the Midwest moves to Los Angeles and gets caught up in the world of acting.',
    cast: ['Bill Hader', 'Stephen Root', 'Sarah Goldberg', 'Henry Winkler'],
    poster: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ended',
    avgRating: 8.5,
    ratingsCount: 11200,
  },
  {
    id: 'tt3526078',
    title: 'Halt and Catch Fire',
    firstAired: 2014,
    creator: 'Christopher Cantwell, Christopher C. Rogers',
    seasons: 4,
    episodes: 40,
    genres: ['Drama'],
    synopsis: 'Set in the early 1980s, the series dramatizes the personal computer revolution through a fictional Texan company navigating the tech industry.',
    cast: ['Lee Pace', 'Scott McNairy', 'Mackenzie Davis', 'Kerry Bishé'],
    poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'AMC',
    status: 'Ended',
    avgRating: 8.3,
    ratingsCount: 6400,
  },
  {
    id: 'tt10234724',
    title: 'The Last of Us',
    firstAired: 2023,
    creator: 'Craig Mazin, Neil Druckmann',
    seasons: 2,
    episodes: 16,
    genres: ['Action', 'Adventure', 'Drama', 'Horror', 'Sci-Fi'],
    synopsis: 'After a global catastrophe caused by a parasitic fungus, a hardened survivor is hired to smuggle a teenage girl out of an oppressive quarantine zone. What starts as a short job soon becomes a brutal, heartbreaking journey.',
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Gabriel Luna', 'Anna Torv'],
    poster: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ongoing',
    avgRating: 8.8,
    ratingsCount: 22800,
  },
  {
    id: 'tt9620292',
    title: 'Andor',
    firstAired: 2022,
    creator: 'Tony Gilroy',
    seasons: 2,
    episodes: 24,
    genres: ['Action', 'Adventure', 'Drama', 'Sci-Fi'],
    synopsis: 'The story of the formation of the Rebellion against the Empire as seen through the eyes of Cassian Andor, a rebel spy whose moral journey stands at the center of this grounded, gritty Star Wars prequel.',
    cast: ['Diego Luna', 'Stellan Skarsgård', 'Adria Arjona', 'Genevieve O\'Reilly'],
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'Disney+',
    status: 'Ended',
    avgRating: 8.5,
    ratingsCount: 14500,
  },
  {
    id: 'tt3032552',
    title: 'Squid Game',
    firstAired: 2021,
    creator: 'Hwang Dong-hyuk',
    seasons: 2,
    episodes: 16,
    genres: ['Action', 'Drama', 'Mystery', 'Thriller'],
    synopsis: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-jun', 'HoYeon Jung'],
    poster: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1527525443983-6e60c75fff46?w=1200&h=600&fit=crop',
    language: 'Korean',
    country: 'South Korea',
    network: 'Netflix',
    status: 'Ongoing',
    avgRating: 8.0,
    ratingsCount: 34100,
  },
  {
    id: 'tt14218830',
    title: 'The White Lotus',
    firstAired: 2021,
    creator: 'Mike White',
    seasons: 3,
    episodes: 22,
    genres: ['Comedy', 'Drama', 'Mystery'],
    synopsis: 'Follows the exploits of various guests and employees of an exclusive tropical resort over the span of a week.',
    cast: ['Murray Bartlett', 'Connie Britton', 'Jennifer Coolidge', 'Alexandra Daddario'],
    poster: 'https://images.unsplash.com/photo-1555548180-61e9b6e44b53?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1500259571355-332da5cb07aa?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ongoing',
    avgRating: 8.0,
    ratingsCount: 13500,
  },
  {
    id: 'tt8134186',
    title: 'Beef',
    firstAired: 2023,
    creator: 'Lee Sung Jin',
    seasons: 1,
    episodes: 10,
    genres: ['Comedy', 'Drama', 'Thriller'],
    synopsis: 'A road rage incident between two strangers — a failing contractor and a successful entrepreneur — spirals into an all-consuming feud that touches the lives of everyone around them.',
    cast: ['Steven Yeun', 'Ali Wong', 'Joseph Lee', 'Young Mazino'],
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'Netflix',
    status: 'Ended',
    avgRating: 8.3,
    ratingsCount: 10100,
  },
  {
    id: 'tt0386676',
    title: 'The Office',
    firstAired: 2005,
    creator: 'Greg Daniels',
    seasons: 9,
    episodes: 201,
    genres: ['Comedy'],
    synopsis: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, romantic conflicts, and inappropriateness.',
    cast: ['Steve Carell', 'Rainn Wilson', 'John Krasinski', 'Jenna Fischer'],
    poster: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'NBC',
    status: 'Ended',
    avgRating: 9.0,
    ratingsCount: 29700,
  },
  {
    id: 'tt1261373',
    title: 'Parks and Recreation',
    firstAired: 2009,
    creator: 'Greg Daniels, Michael Schur',
    seasons: 7,
    episodes: 125,
    genres: ['Comedy'],
    synopsis: 'The absurd antics of an Indiana town\'s public officials as they attempt to make their city a better place.',
    cast: ['Amy Poehler', 'Adam Scott', 'Nick Offerman', 'Rashida Jones'],
    poster: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'NBC',
    status: 'Ended',
    avgRating: 8.6,
    ratingsCount: 18200,
  },
  {
    id: 'tt1632701',
    title: 'Arrested Development',
    firstAired: 2003,
    creator: 'Mitchell Hurwitz',
    seasons: 5,
    episodes: 84,
    genres: ['Comedy'],
    synopsis: 'Level-headed son Michael Bluth takes over family affairs after his father is arrested. But the rest of his spoiled, dysfunctional family are making his job unbearable.',
    cast: ['Jason Bateman', 'Portia de Rossi', 'Will Arnett', 'Michael Cera'],
    poster: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'Fox / Netflix',
    status: 'Ended',
    avgRating: 8.7,
    ratingsCount: 16900,
  },
  {
    id: 'tt4786824',
    title: 'The Crown',
    firstAired: 2016,
    creator: 'Peter Morgan',
    seasons: 6,
    episodes: 60,
    genres: ['Biography', 'Drama', 'History'],
    synopsis: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.',
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton', 'Matt Smith'],
    poster: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1467703834117-04386e3dadd8?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'UK',
    network: 'Netflix',
    status: 'Ended',
    avgRating: 8.6,
    ratingsCount: 15400,
  },
  {
    id: 'tt1844624',
    title: 'American Horror Story',
    firstAired: 2011,
    creator: 'Ryan Murphy, Brad Falchuk',
    seasons: 12,
    episodes: 151,
    genres: ['Drama', 'Horror', 'Thriller'],
    synopsis: 'An anthology series that centers on different characters and locations, including a house with a murderous past, an asylum, a witch coven, a freak show, a hotel, and more.',
    cast: ['Jessica Lange', 'Evan Peters', 'Sarah Paulson', 'Kathy Bates'],
    poster: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'FX',
    status: 'Ongoing',
    avgRating: 8.0,
    ratingsCount: 21500,
  },
  {
    id: 'tt0475784',
    title: 'Westworld',
    firstAired: 2016,
    creator: 'Jonathan Nolan, Lisa Joy',
    seasons: 4,
    episodes: 36,
    genres: ['Drama', 'Mystery', 'Sci-Fi', 'Thriller', 'Western'],
    synopsis: 'Set at the intersection of the near future and the reimagined past, this epic adventure explores a world in which every human appetite, no matter how noble or how depraved, can be indulged.',
    cast: ['Evan Rachel Wood', 'Anthony Hopkins', 'Ed Harris', 'Jeffrey Wright'],
    poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&h=450&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop',
    language: 'English',
    country: 'USA',
    network: 'HBO',
    status: 'Ended',
    avgRating: 8.5,
    ratingsCount: 19300,
  },
];

export const SHOW_MAP = new Map(SHOWS.map(s => [s.id, s]));

export function searchShows(query: string): TVShow[] {
  const q = query.toLowerCase();
  return SHOWS.filter(s =>
    s.title.toLowerCase().includes(q) ||
    s.creator.toLowerCase().includes(q) ||
    s.genres.some(g => g.toLowerCase().includes(q)) ||
    s.cast.some(c => c.toLowerCase().includes(q)) ||
    s.network.toLowerCase().includes(q) ||
    s.firstAired.toString().includes(q)
  );
}

export function getShow(id: string): TVShow | undefined {
  return SHOW_MAP.get(id);
}
